Fix/control response
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-11 pull request #32
Opened 2024-11-09 13:45 UTC by Jukim2

# PR Description

### Sprint No. : 2

### Task ID: U-3

### Description
- Character now stops moving when the key is released
- Added jump functionality
- Added Character animation
- Implemented null checks to prevent runtime errors

## Type of Changes

관련된 사항에 체크해주세요

- [x] 새로운 기능 추가
- [x] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경 사항(오타 수정, 탭 사이즈 변경, 변수명 변경 등)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 작업
- [ ] 테스트 작업 (테스트 케이스 추가, 테스트 코드 리팩토링)
- [ ] 프로젝트 리팩토링 (프로젝트 구조 수정, 폴더명 수정 등)

# Test
테스트 씬에서 동작 테스트 가능하며 기존 움직임 버그는 수정되었고, 애니메이션과 점프도 잘 동작합니다.

# Checklist

- [x] 이 PR의 코드는 프로젝트의 컨벤션을 따릅니다.
- [x] PR 작성자는 본인 코드에 대한 self-review를 마쳤습니다.
- [x] 직관적이지 않은, 이해하기 어려운 부분에 대한 주석을 작성하였습니다.
- [x] 스펙 문서에 해당 변경 사항을 적용했거나, 문서 담당자에게 변경을 요청하였습니다.
- [x] 코드가 프로젝트에 warning이나 error를 유발하지 않았음을 확인하였습니다.
- [x] 수정된 기능을 반영한 테스트가 통과하였습니다.
- [x] 추가된 dependency에 대한 반영을 마쳤습니다.

2024-11-09 15:33 UTC, PJH6029 requested changes
1. 잘 작동되는 것은 확인했습니다. 다만 캐릭터가 마우스따라 회전할 때 약간씩 떨리는데, 제가 해결해보려해도 마땅한 방법이 잘 생각 안나네요.. 
2. `IInputHandler`의 `GetViewDir`에 관한 제안입니다. 확인해보니 `viewDir`가 **실제로 캐릭터가 바라보는 방향 벡터**가 아닌, **해당 방향을 보기 위한 각**이더라구요,  차라리 `viewAngle`로 이름을 바꾸는건 어떤가요?

2024-11-09 16:44 UTC, Jukim2 commented
인벤토리 마무리 지어놓고 확인해보겠습니다

2024-11-10 01:35 UTC, PJH6029 commented
1번은 바꿔야한다는 뜻은 아니었습니다! PR은 2번만 반영되어도 머지해도 될 것 같아요

2024-11-10 02:55 UTC, Jukim2 commented
확인해봤는데 

1번은 turn()을 FixedUpdate에서 Update로 옮기면 해결가능하고 Turn 자체는 물리 상호작용 관련된게 없기때문에 옮겨도 됩니다. 
2번은 GetViewDir자체가 사람이 마우스 혹은 패드로 보는 방향을 가져오고자 한것이라서 viewDir로 써야할 것 같아요.

2024-11-10 03:03 UTC, PJH6029 commented
https://github.com/user-attachments/assets/2ae47865-9f11-4958-b047-ff51e5e52605

헛 그런데 로그 찍어보면, 좌우로 돌리면 벡터의 y값이 변하고, 상하로 돌리면 x값이 변하더라구요

만약 마우스가 보는 방향 자체를 가져오려고 한거면 좌우로 돌리면 (x, z)값이 함께 변하고(y축 기준 회전), 상하로 돌리면 (y, z)값이 함께 변해야하는거(x축 기준 회전) 아닌가요?

2024-11-10 05:15 UTC, Jukim2 commented
아 그러네요

quaternion으로 변환해서 viewRotation을 반환해서 활용하는 걸로 다시 푸쉬하면 될 것 같은데 그렇게할까요?

2024-11-10 08:07 UTC, PJH6029 commented
네 좋습니다!

2024-11-11 05:39 UTC, closed without merging